### PR TITLE
Get dishes from restaurant

### PR DESCRIPTION
**Pull request by callea2**
PT Story: https://www.pivotaltracker.com/story/show/124541361
- Set up tests (request specs) for the API endpoints
- Set up controllers for API endpoints

### CODE REVIEW

**Comment by diraulo** [comment]
@flamesoft @callea2 what if I want to get a single dish say by id or name? or it's not required at this stage of the development?

**Comment by flamesoft** [comment]
@diraulo thanks for reminding. We will add this function.

**Comment by diraulo** [comment]
okay .. that's probably beyond the scope of this story. I would create a separate issue to deal with it maybe

**Comment by diraulo** [comment]
@tochman any comments on this?

**Pull request merged**
