### PR TITLE
Set up CI server

### PR DESCRIPTION
**Pull request by flamesoft**
PT: https://www.pivotaltracker.com/story/show/121669297
- Register project for Coveralls

### CODE REVIEW

**Comment by diraulo** [comment]
@flamesoft You shouldn't check `coverage` folder into version control. It should be added to the `.gitignore` file

**Comment by tochman** [comment]
Was just about to mention that @diraulo

**Comment by tochman** [comment]
Now we also need to clear it from the cached files.

**Comment by flamesoft** [comment]
I will fix that.

**Pull request merged**
