### PR TITLE
Choose Template engine - We will be using Haml as our Template Engine

### PR DESCRIPTION
**Pull request by DanielitoAlbinsson**
PT story: https://www.pivotaltracker.com/story/show/121741137

### CODE REVIEW

**Comment by tochman** [comment]
Okay so the two first commits should not be in this PR. Each feature branch should originate from upstream/development.

**Comment by DanielitoAlbinsson** [comment]
ok so what should i do?

**Comment by tochman** [comment]
We fix this by using cherry-pick and get a clean commit history

**Comment by tochman** [comment]
Can we merge this @callea2 @flamesoft ? I have no objections. @DanielitoAlbinsson Have you updated PT with a link to the PR and checked all acceptance criteria?

**Comment by diraulo** [comment]
:shipit:

**Pull request merged**
