### PR TITLE
Menus

### PR DESCRIPTION
**Pull request by flamesoft**
PT story: https://www.pivotaltracker.com/story/show/122039015
- Every dish belongs to a menu
- Restaurant show page shows all the menus' names for the restaurant 
- Dishes should be displayed under a specific menu. After clicking a menu's name on the Restaurant show page, it goes to a page listing all the dishes belonging to the menu

### CODE REVIEW

**Comment by diraulo** [comment]
Looks good to me :shipit:

**Comment by tochman** [comment]
I'm sorry to say but this PR contains the same commits as https://github.com/CraftAcademy/slow_food_online/pull/25 This is due to the way you have created this feature branch @flamesoft You should have switched to your local development branch first and then created the `menu` branch (we wnt over this flow a few times during this project)  That is a problem because we squash commits when we merge Pull requests and all commits in https://github.com/CraftAcademy/slow_food_online/pull/25 are now in https://github.com/CraftAcademy/slow_food_online/commit/d55d20a300dc9647f1fc238b8c19d0a3bcc3e315 
The only way to solve this is to create a new feature branch off development and cherry pick all commits from this branch that ware not part of the previous PR.

**Comment by tochman** [comment]
And then create a new PR or `-force` your changes to this branch and thus update this PR. We did this on one of @callea2 PR before as well as one of the PR's that @DanielitoAlbinsson created.

**Comment by diraulo** [comment]
@tochman I missed that..

**Comment by flamesoft** [comment]
I will open a new pull request on the same user story.

**Pull request closed without merging**
